title: Build Things Together
subtitle: Bill Mills
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

#url: x
baseurl: "http://billmills.github.io/blog"
paginate_path: "blog/page:num/"
permalink: blog/:title/

highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 #- title: About
 #  url: /about
 #- title: Twitter
 #  url: https://twitter.com/billdoesphysics

social:
   github: BillMills
   twitter: billdoesphysics
   email: mills.wj@gmail.com

google_analytics: "UA-58263416-1"
future: true
